name: Integrate Changes
on:
  workflow_dispatch:
  push:
    branches-ignore: 
    - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Restore Packages
      run: dotnet restore

    - name: Build Solution
      run: dotnet build -c Release --no-restore

    - name: Test Solution
      run: dotnet test -c Release --no-build