name: Integrate Changes
on:
  workflow_dispatch:
  push:
    branches-ignore: 
    - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore Packages
      run: nuget restore 'Simple Data Storage Engine.sln'

    - name: Build Solution
      run: msbuild 'Simple Data Storage Engine.sln' -t:rebuild -property:Configuration=Release

    - name: Test Solution
      uses: microsoft/vstest-action@v1.0.0
      with:
        testAssembly: '*.Tests.dll'
        searchFolder: '.\*.Tests\bin\Debug\'
        runInParallel: true